# -*- coding: utf-8 -*-
"""Neural Network Job

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHKk2qg8RX3nTmdmxioAxvjF15O_0uiT
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

url = tf.keras.utils.get_file('aug_train.csv', 'https://raw.githubusercontent.com/ImDatAsian/Neural-Network-Looking-For-Job/main/aug_train.csv')

df = pd.read_csv(url)

dum_rel_exp = pd.get_dummies(df['Relevent Experience'])
dum_en_un = pd.get_dummies(df['Enrolled University'])
dum_ed_lvl = pd.get_dummies(df['Education Level'])
dum_c_m = pd.get_dummies(df['College Major'])
dum_exp = pd.get_dummies(df['Experience'])
dum_c_s = pd.get_dummies(df['Company Size'])
dum_c_t = pd.get_dummies(df['Company Type'])
dum_l_n_t = pd.get_dummies(df['Last New Job'])

df = pd.merge(
    left=df,
    right=dum_rel_exp,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_en_un,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_ed_lvl,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_c_m,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_exp,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_c_s,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_c_t,
    left_index=True,
    right_index=True,
)
df = pd.merge(
    left=df,
    right=dum_l_n_t,
    left_index=True,
    right_index=True,
)

df = df.drop(columns=['Enrollee Id','Gender', 'City','Relevent Experience','Enrolled University','Education Level','College Major','Experience','Company Size','Company Type','Last New Job'])

target = df.pop('Target')

train, val, test = np.split(df.sample(frac=1, random_state=1),
                            [int(.7*len(df)), int(.85*len(df))])

train_target, val_target, test_target = np.split(target.sample(frac=1, random_state=1),
                                                 [int(.7*len(df)), int(.85*len(df))])

train_dataset = tf.data.Dataset.from_tensor_slices((train.values, train_target.values))
validate_dataset = tf.data.Dataset.from_tensor_slices((val.values, val_target.values))
test_dataset = tf.data.Dataset.from_tensor_slices((test.values, test_target.values))

train_ds = train_dataset.shuffle(len(train)).batch(64)
val_ds = validate_dataset.batch(32)
test_ds = test_dataset.batch(128)

model = tf.keras.Sequential([
                             layers.Dense(128, activation='linear'),
                             layers.Dense(128, activation='linear'),
                             layers.Dense(2, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


model.fit(train_ds, validation_data=val_ds, epochs=60)

model.evaluate(test_ds)

df.to_csv('aug_train_cleaned')

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""